const countries = {
    canada : 'ca',
    unitedkingdom : 'uk',
    unitedstatesofamerica : 'us',
    afghanistan : 'af',
    albania : 'al',
    algeria : 'dz',
    americansamoa : 'as',
    andorra : 'ad',
    angola : 'ao',
    anguilla : 'ai',
    antarctica : 'aq',
    antiguaandbarbuda : 'ag',
    argentina : 'ar',
    armenia : 'am',
    aruba : 'aw',
    australia : 'au',
    austria : 'at',
    azerbaijan : 'az',
    bahamas : 'bs',
    bahrain : 'bh',
    bangladesh : 'bd',
    barbados : 'bb',
    belarus : 'by',
    belgium : 'be',
    belize : 'bz',
    benin : 'bj',
    bermuda : 'bm',
    bhutan : 'bt',
    bolivia : 'bo',
    bosniaandherzegovina : 'ba',
    botswana : 'bw',
    brazil : 'br',
    bruneidarussalam : 'bn',
    bulgaria : 'bg',
    burkinafaso : 'bf',
    burundi : 'bi',
    cambodia : 'kh',
    cameroon : 'cm',
    caymanislands : 'ky',
    centralafricanrepublic : 'cf',
    chad : 'td',
    chile : 'cl',
    china : 'cn',
    colombia : 'co',
    comoros : 'km',
    congo : 'cd',
    costarica : 'cr',
    croatia : 'hr',
    cuba : 'cu',
    curaçao : 'cw',
    cyprus : 'cy',
    czechia : 'cz',
    cotedivoire : 'ci',
    denmark : 'dk',
    djibouti : 'dj',
    dominica : 'dm',
    dominicanrepublic : 'do',
    ecuador : 'ec',
    egypt : 'eg',
    elsalvador : 'sv',
    equatorialguinea : 'gq',
    eritrea : 'er',
    estonia : 'ee',
    eswatini : 'sz',
    ethiopia : 'et',
    fiji : 'fj',
    finland : 'fi',
    france : 'fr',
    frenchguiana : 'gf',
    gabon : 'ga',
    gambia : 'gm',
    georgia : 'ge',
    germany : 'de',
    ghana : 'gh',
    gibraltar : 'gi',
    greece : 'gr',
    greenland : 'gl',
    grenada : 'gd',
    guadeloupe : 'gp',
    guam : 'gu',
    guatemala : 'gt',
    guinea : 'gn',
    guineabissau : 'gw',
    guyana : 'gy',
    haiti : 'ht',
    honduras : 'hn',
    hongkong : 'hk',
    hungary : 'hu',
    iceland : 'is',
    india : 'in',
    indonesia : 'id',
    iran : 'ir',
    iraq : 'iq',
    ireland : 'ie',
    israel : 'il',
    italy : 'it',
    jamaica : 'jm',
    japan : 'jp',
    jordan : 'jo',
    kazakhstan : 'kz',
    kenya : 'ke',
    kiribati : 'ki',
    korea : 'kr',
    kuwait : 'kw',
    kyrgyzstan : 'kg',
    laos : 'la',
    latvia : 'lv',
    lebanon : 'lb',
    lesotho : 'ls',
    liberia : 'lr',
    libya : 'ly',
    liechtenstein : 'li',
    lithuania : 'lt',
    luxembourg : 'lu',
    macao : 'mo',
    madagascar : 'mg',
    malawi : 'mw',
    malaysia : 'my',
    maldives : 'mv',
    mali : 'ml',
    malta : 'mt',
    martinique : 'mq',
    mauritania : 'mr',
    mauritius : 'mu',
    mayotte : 'yt',
    mexico : 'mx',
    moldova : 'md',
    monaco : 'mc',
    mongolia : 'mn',
    montenegro : 'me',
    montserrat : 'ms',
    morocco : 'ma',
    mozambique : 'mz',
    myanmar : 'mm',
    namibia : 'na',
    nauru : 'nr',
    nepal : 'np',
    netherlands : 'nl',
    newzealand : 'nz',
    nicaragua : 'ni',
    niger : 'ne',
    nigeria : 'ng',
    niue : 'nu',
    norway : 'no',
    oman : 'om',
    pakistan : 'pk',
    palau : 'pw',
    palestine : 'ps',
    panama : 'pa',
    papuanewguinea : 'pg',
    paraguay : 'py',
    peru : 'pe',
    philippines : 'ph',
    pitcairn : 'pn',
    poland : 'pl',
    portugal : 'pt',
    puertorico : 'pr',
    qatar : 'qa',
    macedonia : 'mk',
    romania : 'ro',
    russia : 'ru',
    rwanda : 'rw',
    réunion : 're',
    saintkittsandnevis : 'kn',
    saintlucia : 'lc',
    samoa : 'ws',
    sanmarino : 'sm',
    saotomeandprincipe : 'st',
    saudiarabia : 'sa',
    senegal : 'sn',
    serbia : 'rs',
    seychelles : 'sc',
    sierraleone : 'sl',
    singapore : 'sg',
    slovakia : 'sk',
    slovenia : 'si',
    solomonislands : 'sb',
    somalia : 'so',
    southafrica : 'za',
    southsudan : 'ss',
    spain : 'es',
    srilanka : 'lk',
    sudan : 'sd',
    suriname : 'sr',
    sweden : 'se',
    switzerland : 'ch',
    syrianarabrepublic : 'sy',
    taiwan : 'tw',
    tajikistan : 'tj',
    tanzania : 'tz',
    thailand : 'th',
    togo : 'tg',
    tokelau : 'tk',
    tonga : 'to',
    trinidadandtobago : 'tt',
    tunisia : 'tn',
    turkey : 'tr',
    turkmenistan : 'tm',
    tuvalu : 'tv',
    uganda : 'ug',
    ukraine : 'ua',
    unitedarabemirates: 'ae',
    uruguay : 'uy',
    uzbekistan : 'uz',
    vanuatu : 'vu',
    venezuela : 've',
    vietnam : 'vn',
    westernsahara : 'eh',
    yemen : 'ye',
    zambia : 'zm',
    zimbabwe : 'zw',
}

const countryNames = ['Canada',
'United Kingdom',
'United States of America',
'Afghanistan',
'Albania',
'Algeria',
'American Samoa',
'Andorra',
'Angola',
'Anguilla',
'Antarctica',
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Aruba',
'Australia',
'Austria',
'Azerbaijan',
'Bahamas',
'Bahrain',
'Bangladesh',
'Barbados',
'Belarus',
'Belgium',
'Belize',
'Benin',
'Bermuda',
'Bhutan',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Brazil',
'Brunei Darussalam',
'Bulgaria',
'Burkina Faso',
'Burundi',
'Cambodia',
'Cameroon',
'Cayman Islands',
'Central African Republic',
'Chad',
'Chile',
'China',
'Colombia',
'Comoros',
'Congo (the Democratic Republic of the)',
'Costa Rica',
'Croatia',
'Cuba',
'Curaçao',
'Cyprus',
'Czechia',
'Côte d Ivoire',
'Denmark',
'Djibouti',
'Dominica',
'Dominican Republic',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Eswatini',
'Ethiopia',
'Fiji',
'Finland',
'France',
'French Guiana',
'Gabon',
'Gambia',
'Georgia',
'Germany',
'Ghana',
'Gibraltar',
'Greece',
'Greenland',
'Grenada',
'Guadeloupe',
'Guam',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Honduras',
'Hong Kong',
'Hungary',
'Iceland',
'India',
'Indonesia',
'Iran',
'Iraq',
'Ireland',
'Israel',
'Italy',
'Jamaica',
'Japan',
'Jordan',
'Kazakhstan',
'Kenya',
'Kiribati',
'Korea (Republic of)',
'Kuwait',
'Kyrgyzstan',
'Laos',
'Latvia',
'Lebanon',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Macao',
'Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Martinique',
'Mauritania',
'Mauritius',
'Mayotte',
'Mexico',
'Moldova',
'Monaco',
'Mongolia',
'Montenegro',
'Montserrat',
'Morocco',
'Mozambique',
'Myanmar',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'Niue',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Palestine',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Pitcairn',
'Poland',
'Portugal',
'Puerto Rico',
'Qatar',
'Macedonia',
'Romania',
'Russia',
'Rwanda',
'Réunion',
'Saint Kitts and Nevis',
'Saint Lucia',
'Samoa',
'San Marino',
'Sao Tome and Principe',
'Saudi Arabia',
'Senegal',
'Serbia',
'Seychelles',
'Sierra Leone',
'Singapore',
'Slovakia',
'Slovenia',
'Solomon Islands',
'Somalia',
'South Africa',
'South Sudan',
'Spain',
'Sri Lanka',
'Sudan',
'Suriname',
'Sweden',
'Switzerland',
'Syrian Arab Republic',
'Taiwan',
'Tajikistan',
'Tanzania',
'Thailand',
'Togo',
'Tokelau',
'Tonga',
'Trinidad and Tobago',
'Tunisia',
'Turkey',
'Turkmenistan',
'Tuvalu',
'Uganda',
'Ukraine',
'United Arab Emirates',
'Uruguay',
'Uzbekistan',
'Vanuatu',
'Venezuela (Bolivarian Republic of)',
'Vietnam',
'Western Sahara',
'Yemen',
'Zambia',
'Zimbabwe']